---
pagetitle: "DIA Lab"
# main-photo: /assets/aadam-2021-square.jpg
# main-photo-square: /assets/aadam-2021-square.jpg
page-layout: full
---

::: {.hero}
# Welcome to Document Image Analysis Lab
## Indian Institute of Technology Jodhpur

## Our Mission

Welcome to the **DIA Lab** Our laboratory is dedicated to advancing the field of Document Image Analysis (DIA) through cutting-edge research, innovation, and collaboration. We are committed to exploring the multifaceted challenges posed by document processing and developing state-of-the-art solutions that leverage computer vision, machine learning, and natural language processing techniques. With a team of passionate researchers and access to a wealth of resources, our lab strives to make significant contributions to areas such as document recognition, handwriting analysis, document layout understanding, and more. Our mission is to enhance the efficiency and accuracy of document-related tasks, benefiting a wide range of industries, from academia to industry. We invite you to explore our research projects, publications, and join us in our pursuit of excellence in Document Image Analysis.
:::

