---
title: "Publications"
page-layout: full
title-block-banner: true
---

(Full list of publications can be found [here](https://pubmed.ncbi.nlm.nih.gov/?term=Masood+A))

1.  [Correction: Refining colorectal cancer classification and clinical stratification through a single-cell atlas](https://pubmed.ncbi.nlm.nih.gov/35831907/) Khaliq AM, Erdogan C, Kurt Z, Turgut SS, Grunvald MW, Rand T, Khare S, Borgia JA, Hayden DM, Pappas SG, Govekar HR, Kam AE, Reiser J, Turaga K, Radovich M, Zang Y, Qiu Y, Liu Y, Fishel ML, Turk A, Gupta V, Al-Sabti R, Subramanian J, Kuzel TM, Sadanandam A, Waldron L, Hussain A, Saleem M, El-Rayes B, Salahudeen AA, **Masood A.** _Genome Biol . 2022 Jul 13;23(1):156. doi: 10.1186/s13059-022-02724-9._
2.  [Current and emerging therapies for advanced biliary tract cancers](https://pubmed.ncbi.nlm.nih.gov/34626563/) Audrey E Kam 1 , **Ashiq Masood** 2 , Rachna T Shroff 3 _Lancet Gastroenterol Hepatol . 2021 Nov;6(11):956-969_ .
3.  [Genomic Profiling of Lung Adenocarcinoma in Never-Smokers](https://pubmed.ncbi.nlm.nih.gov/34591593/) Devarakonda S,Li Y,Martins Rodrigues F,Sankararaman S,Kadara H,Goparaju C,Lanc I,Pepin K,Waqar SN,Morgensztern D,Ward J,**Masood A**,Fulton R,Fulton L,Gillette MA,Satpathy S,Carr SA,Wistuba I,Pass H,Wilson RK,Ding L,Govindan R. _J Clin Oncol . 2021 Nov 20;39(33):3747-3758. doi: 10.1200/JCO.21.01691_
4.  [A pan-cancer organoid platform for precision medicine](https://pubmed.ncbi.nlm.nih.gov/34320344/) Larsen BM,Kannan M,Langer LF,Leibowitz BD,Bentaieb A,Cancino A,Dolgalev I,Drummond BE,Dry JR,Ho CS,Khullar G,Krantz BA,Mapes B,McKinnon KE,Metti J,Perera JF,Rand TA,Sanchez-Freire V,Shaxted JM,Stein MM,Streit MA,Tan YC,Zhang Y,Zhao E,Venkataraman J,Stumpe MC,Borgia JA,**Masood A**,Catenacci DVT,Mathews JV,Gursel DB,Wei JJ,Welling TH,Simeone DM,White KP,Khan AA,Igartua C,Salahudeen AA. _Cell Rep 2021 07 27;36(4): 109429. doi: S2211-1247(21)00846-9_
5.  [Non-secretory multiple myeloma with unusual TFG-ALK fusion showed dramatic response to ALK inhibition](https://pubmed.ncbi.nlm.nih.gov/33731690/) **Masood A**,Christ T,Asif S,Rajakumar P,Gustafson BA,Shune LO,Salahudeen A,Nedvad D,Nanua S,Paner A,Kuzel TM,Levy M,Subramanian J,Raza S. _NPJ Genom Med 2021 Mar 17;6(1): 23. doi: 10.1038/s41525-021-00186-9_
6.  [The Prognostic Role of the Neutrophil to Lymphocyte Ratio at Recurrence in Esophageal Squamous Cell Carcinoma: Challenges and Future Directions](https://pubmed.ncbi.nlm.nih.gov/33560489/) Kam AE,**Masood A**. _Ann Surg Oncol 2021 Jun ;28(6): 2939-2940. doi: 10.1245/s10434-021-09640-5_
7.  [Current Status of Circulating Tumor DNA Liquid Biopsy in Pancreatic Cancer](https://pubmed.ncbi.nlm.nih.gov/33081107/) Grunvald MW,Jacobson RA,Kuzel TM,Pappas SG,**Masood A**. _Int J Mol Sci 2020 Oct 16;21(20): . doi: ijms21207651_
8.  [Postoperative Chemotherapy for Thoracic Pathological T3N0M0 Esophageal Squamous Cell Carcinoma](https://pubmed.ncbi.nlm.nih.gov/31848823/) Kam AE,Pappas SG,**Masood A**. _Ann Surg Oncol 2020 May ;27(5): 1314-1315. doi: 10.1245/s10434-019-08140-x_
9.  [Epidermal growth factor receptor (EGFR) tyrosine kinase inhibitors in non-small cell lung cancer harboring uncommon EGFR mutations: Focus on afatinib](https://pubmed.ncbi.nlm.nih.gov/31558282/) **Masood A**,Kancha RK,Subramanian J. _Semin Oncol 2019 06 ;46(3): 271-283. doi: S0093-7754(18)30191-X_
10.  [Matched Whole-Genome Sequencing (WGS) and Whole-Exome Sequencing (WES) of Tumor Tissue with Circulating Tumor DNA (ctDNA) Analysis: Complementary Modalities in Clinical Practice](https://pubmed.ncbi.nlm.nih.gov/31546879/) Imperial R,Nazer M,Ahmed Z,Kam AE,Pluard TJ,Bahaj W,Levy M,Kuzel TM,Hayden DM,Pappas SG,Subramanian J,**Masood A**. _Cancers (Basel) 2019 Sep 19;11(9): . doi: cancers11091399_
11.  [Radiation Recall in a Patient with Intrahepatic Cholangiocarcinoma: Case Report and a Literature Review](https://pubmed.ncbi.nlm.nih.gov/31497449/) Bahaj W,Ya'qoub L,Toor M,**Masood A**. _Cureus 2019 Jun 27;11(6): e5020. doi: 10.7759/cureus.5020_
12.  [Evolving Clinical Utility of Liquid Biopsy in Gastrointestinal Cancers](https://pubmed.ncbi.nlm.nih.gov/31412682/) Jacobson RA,Munding E,Hayden DM,Levy M,Kuzel TM,Pappas SG,**Masood A**. _Cancers (Basel) 2019 Aug 13;11(8): . doi: cancers11081164_
13.  [Emergence of ERBB2 Mutation as a Biomarker and an Actionable Target in Solid Cancers](https://pubmed.ncbi.nlm.nih.gov/31292270/) Subramanian J,Katta A,**Masood A**,Vudem DR,Kancha RK. _Oncologist 2019 12 ;24(12): e1303-e1314. doi: theoncologist.2018-0845_
14.  [Pembrolizumab in newly diagnosed EBV-negative extranodal natural killer/T-cell lymphoma: A case report](https://pubmed.ncbi.nlm.nih.gov/30847181/) Asif S,Begemann M,Bennett J,Fatima R,**Masood A**,Raza S. _Mol Clin Oncol 2019 Mar ;10(3): 397-400. doi: 10.3892/mco.2019.1805_
15.  [Comparative proteogenomic analysis of right-sided colon cancer, left-sided colon cancer and rectal cancer reveals distinct mutational profiles](https://pubmed.ncbi.nlm.nih.gov/30577807/) Imperial R,Ahmed Z,Toor OM,Erdoğan C,Khaliq A,Case P,Case J,Kennedy K,Cummings LS,Melton N,Raza S,Diri B,Mohammad R,El-Rayes B,Pluard T,Hussain A,Subramanian J,**Masood A**. _Mol Cancer 2018 12 21;17(1): 177. doi: 10.1186/s12943-018-0923-9_
16.  [Recurrent WNT pathway alterations are frequent in relapsed small cell lung cancer](https://pubmed.ncbi.nlm.nih.gov/30224629/) Wagner AH,Devarakonda S,Skidmore ZL,Krysiak K,Ramu A,Trani L,Kunisaki J,**Masood A**,Waqar SN,Spies NC,Morgensztern D,Waligorski J,Ponce J,Fulton RS,Maggi LB,Weber JD,Watson MA,O'Conor CJ,Ritter JH,Olsen RR,Cheng H,Mukhopadhyay A,Can I,Cessna MH,Oliver TG,Mardis ER,Wilson RK,Griffith M,Griffith OL,Govindan R. _Nat Commun 2018 09 17;9(1): 3787. doi: 10.1038/s41467-018-06162-9_
17.  [Tumor Mutation Burden as a Biomarker in Resected Non-Small-Cell Lung Cancer](https://pubmed.ncbi.nlm.nih.gov/30106638/) Devarakonda S,Rotolo F,Tsao MS,Lanc I,Brambilla E,**Masood A**,Olaussen KA,Fulton R,Sakashita S,McLeer-Florin A,Ding K,Le Teuff G,Shepherd FA,Pignon JP,Graziano SL,Kratzke R,Soria JC,Seymour L,Govindan R,Michiels S. _J Clin Oncol 2018 10 20;36(30): 2995-3006. doi: 10.1200/JCO.2018.78.1963_
18.  [The evolving genomic landscape in urothelial cancer](https://pubmed.ncbi.nlm.nih.gov/29538042/) Kujtan L,Hussain A,Subramanian J,**Masood A**. _Curr Opin Oncol 2018 05 ;30(3): 197-202. doi: 10.1097/CCO.0000000000000447_
19.  [Correlation of Somatic Genomic Alterations Between Tissue Genomics and ctDNA Employing Next-Generation Sequencing: Analysis of Lung and Gastrointestinal Cancers](https://pubmed.ncbi.nlm.nih.gov/29500272/) Toor OM,Ahmed Z,Bahaj W,Boda U,Cummings LS,McNally ME,Kennedy KF,Pluard TJ,Hussain A,Subramanian J,**Masood A.** _Mol Cancer Ther 2018 05 ;17(5): 1123-1132. doi: 1535-7163.MCT-17-1015_