---
title: "Our Research"
title-block-banner: true
---

At **DIA Lab**, we are driven by a relentless curiosity to explore and address the intricate challenges within the realm of document processing. Our research endeavors are at the forefront of innovation in Document Image Analysis (DIA), encompassing a wide array of areas that have a profound impact on how we interact with textual and visual information. 
Our dedicated team of researchers collaborates intensively on projects that span from fundamental studies in optical character recognition (OCR) and text extraction to more complex tasks such as document layout understanding, signature verification, and historical document preservation. We are passionate about pushing the boundaries of computer vision, machine learning, and natural language processing to develop cutting-edge solutions that revolutionize document-related processes across industries.
With a commitment to excellence, we actively publish our findings in prestigious journals and conferences, contributing to the academic community's body of knowledge in DIA. Moreover, we foster partnerships with industry leaders, government agencies, and academic institutions, ensuring that our research finds practical applications that benefit society at large.
Our research is not limited to the confines of our lab; it extends to the development of open-source tools and resources that empower researchers and practitioners worldwide. Through our contributions, we strive to make document-related tasks more efficient, accurate, and accessible.
We invite you to delve into the details of our ongoing projects and explore our publications to gain insight into the exciting world of Document Image Analysis. Join us on this journey of discovery and innovation, where the power of technology meets the intricacies of document processing, unlocking new possibilities and efficiencies for a myriad of fields and industries. Thank you for your interest in our research, and we look forward to sharing our progress and insights with you.